/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as QualityRouteImport } from './routes/quality'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FactoryRouteImport } from './routes/factory'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommunityImpactRouteImport } from './routes/community-impact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as OurPartnersRouteImport } from './routes/OurPartners'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const QualityRoute = QualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FactoryRoute = FactoryRouteImport.update({
  id: '/factory',
  path: '/factory',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityImpactRoute = CommunityImpactRouteImport.update({
  id: '/community-impact',
  path: '/community-impact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const OurPartnersRoute = OurPartnersRouteImport.update({
  id: '/OurPartners',
  path: '/OurPartners',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/OurPartners': typeof OurPartnersRoute
  '/about': typeof AboutRoute
  '/community-impact': typeof CommunityImpactRoute
  '/contact': typeof ContactRoute
  '/factory': typeof FactoryRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/products': typeof ProductsRoute
  '/quality': typeof QualityRoute
  '/services': typeof ServicesRoute
  '/team': typeof TeamRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/OurPartners': typeof OurPartnersRoute
  '/about': typeof AboutRoute
  '/community-impact': typeof CommunityImpactRoute
  '/contact': typeof ContactRoute
  '/factory': typeof FactoryRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/products': typeof ProductsRoute
  '/quality': typeof QualityRoute
  '/services': typeof ServicesRoute
  '/team': typeof TeamRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/OurPartners': typeof OurPartnersRoute
  '/about': typeof AboutRoute
  '/community-impact': typeof CommunityImpactRoute
  '/contact': typeof ContactRoute
  '/factory': typeof FactoryRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/products': typeof ProductsRoute
  '/quality': typeof QualityRoute
  '/services': typeof ServicesRoute
  '/team': typeof TeamRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/OurPartners'
    | '/about'
    | '/community-impact'
    | '/contact'
    | '/factory'
    | '/faq'
    | '/gallery'
    | '/products'
    | '/quality'
    | '/services'
    | '/team'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/OurPartners'
    | '/about'
    | '/community-impact'
    | '/contact'
    | '/factory'
    | '/faq'
    | '/gallery'
    | '/products'
    | '/quality'
    | '/services'
    | '/team'
    | '/blog/$slug'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/OurPartners'
    | '/about'
    | '/community-impact'
    | '/contact'
    | '/factory'
    | '/faq'
    | '/gallery'
    | '/products'
    | '/quality'
    | '/services'
    | '/team'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OurPartnersRoute: typeof OurPartnersRoute
  AboutRoute: typeof AboutRoute
  CommunityImpactRoute: typeof CommunityImpactRoute
  ContactRoute: typeof ContactRoute
  FactoryRoute: typeof FactoryRoute
  FaqRoute: typeof FaqRoute
  GalleryRoute: typeof GalleryRoute
  ProductsRoute: typeof ProductsRoute
  QualityRoute: typeof QualityRoute
  ServicesRoute: typeof ServicesRoute
  TeamRoute: typeof TeamRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quality': {
      id: '/quality'
      path: '/quality'
      fullPath: '/quality'
      preLoaderRoute: typeof QualityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/factory': {
      id: '/factory'
      path: '/factory'
      fullPath: '/factory'
      preLoaderRoute: typeof FactoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community-impact': {
      id: '/community-impact'
      path: '/community-impact'
      fullPath: '/community-impact'
      preLoaderRoute: typeof CommunityImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/OurPartners': {
      id: '/OurPartners'
      path: '/OurPartners'
      fullPath: '/OurPartners'
      preLoaderRoute: typeof OurPartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OurPartnersRoute: OurPartnersRoute,
  AboutRoute: AboutRoute,
  CommunityImpactRoute: CommunityImpactRoute,
  ContactRoute: ContactRoute,
  FactoryRoute: FactoryRoute,
  FaqRoute: FaqRoute,
  GalleryRoute: GalleryRoute,
  ProductsRoute: ProductsRoute,
  QualityRoute: QualityRoute,
  ServicesRoute: ServicesRoute,
  TeamRoute: TeamRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
